version: '3.8'

services:
  web:
    image: vijayarajvira/hello-docker:latest
    ports:
      - "8081:80"
    restart: always

  api:
    image: vijayarajvira/hello-docker:latest
    command: ["node", "/api/server.js"]
    ports:
      - "3000:3000"
    restart: always










